### ISSUE TITLE
Ubuntu Clone

### ISSUE THREAD

**Issue by TheColorfulGamer** [Takkapi/TakkapiOS#2]
Hi. Your operating system looks like Ubuntu
![Screenshot_Desktop_Ubuntu_20 04_Focal_Fossa_2160p](https://user-images.githubusercontent.com/65781275/106359474-b5c84580-631b-11eb-8259-d7d5186ff57c.png)
Please fix this

**Comment by Takkapi** [comment]
Hi. Thanks for reporting. This is a mistake, we will try to fix this as soon as posible.
Our OS should look like this 
![image](https://user-images.githubusercontent.com/72162635/106359561-443cc700-631c-11eb-90dd-1a8f59fbe58c.png)
