### ISSUE TITLE
Ubuntu clone

### ISSUE THREAD

**Issue by TheColorfulGamer** [Takkapi/TakkapiOS#3]
Hi, Your operating system looks like ubuntu
![Screenshot_Desktop_Ubuntu_20 04_Focal_Fossa_2160p](https://user-images.githubusercontent.com/65781275/106359631-9d0c5f80-631c-11eb-85e6-3310cb4592bf.png)
Please fix this

**Comment by Takkapi** [comment]
Hi. Thanks for reporting. We will try as soon as posible to fix this.
![image](https://user-images.githubusercontent.com/72162635/106359679-d644cf80-631c-11eb-94ef-3656d74d3952.png)
